db:
  image: postgres
  container_name: db
  environment:
    - POSTGRES_PASSWORD=postgres
app:
  image: delermando/nginx-php5-fpm
  container_name: app
  ports:
    - "8080:80"
  links:
    - db
  volumes:
    - .:/app
    - ./app/docker-compose/entrypoint.sh:/usr/local/bin/entrypoint.sh
